Add a signal handler to the entrypoint of the Inmanta container to correctly handle the termination of the container (PR #96)
# Description

Add a signal handler to the entrypoint of the Inmanta container to correctly handle the termination of the container.

I will create similar PR on the inmanta-service-orchestrator repository if this one gets approved.

closes #87

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry

diff --git a/docker/resources/container-entrypoint-with-env b/docker/resources/container-entrypoint-with-env
--- a/docker/resources/container-entrypoint-with-env
+++ b/docker/resources/container-entrypoint-with-env
@@ -1,5 +1,37 @@
 #!/bin/bash
 
+pid_su_start_server=-1
+stop_container(){
+    if [ ${pid_su_start_server} -ge 0 ]; then
+        # Stop Inmanta server gracefully
+        kill ${pid_su_start_server}
+        wait ${pid_su_start_server}
+    fi
+    exit 0
+}
+# Make sure that the stop_container signal handle fires on the SIGTERM and SIGINT signal.
+trap stop_container TERM INT
+
+execute_long_running_command() {
+    # When Bash is executing a command, it queues all signals that occur while
+    # that command is executing. When the command finishes, the signals are processed.
+    # This way it can take a long time between the moment the ctrl-c interrupt/docker stop
+    # is executed by the user and the actual termination of the container. This function
+    # provides functionality to ensure that signals are processed while a command is executing.
+    # Commands that take a long time to execute should always use this function.
+    #
+    # :params: The command to be executed
+    # :return: The exit code of this function is the exit code of the executed command.
+    local cmd="$*"
+    eval ${cmd} &
+    local pid=$!
+    # Wait until the background task finishes execution.
+    # The `wait` command gets interrupted when a signal fires.
+    wait ${pid}
+    local exit_code_cmd=$?
+    return ${exit_code_cmd}
+}
+
 # Setting up the inmanta working environment
 source /usr/bin/load-inmanta-env
 
@@ -136,7 +168,7 @@ wait_for_host_port()
     yellow "Will wait at most $max_attempts seconds for $host:$port to become reachable"
 
     count=0
-    until nc -z -v -w30 "$host" "$port" || [ $count -ge $max_attempts ]
+    until execute_long_running_command nc -z -v -w30 "$host" "$port" || [ $count -ge $max_attempts ]
     do
         sleep 1
         count=$(( $count+1 ))
@@ -149,9 +181,11 @@ wait_for_host_port()
 }
 
 # Start the inmanta server as an inmanta user
-start_server() 
+start_server()
 {
-    sudo -i -u inmanta /usr/bin/inmanta -vvv --timed-logs server
+   su -l inmanta -c '/usr/bin/inmanta -vvv --timed-logs server' &
+   pid_su_start_server=$!
+   wait ${pid_su_start_server}
 }
 
 # MAIN SECTION
